<?php

namespace Database\Seeders;

use App\Models\Individual;
use Illuminate\Database\Seeder;

class IndividualSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $individuals = [
            [
                'national_id' => 'V-12345678',
                'first_name' => 'María',
                'middle_name' => 'José',
                'last_name' => 'Rodríguez',
                'second_last_name' => 'Gómez',
                'birth_date' => '1980-05-15',
                'gender' => 'female',
                'civil_status' => 'married',
                'rif' => 'V-123456789',
                'email_1' => 'maria.rodriguez@ejemplo.com',
                'phone_number_1' => '0414-1234567',
                'address_line_1' => 'Av. Francisco de Miranda',
                'city' => 'Caracas',
                'state' => 'Distrito Capital',
                'occupation' => 'Abogada',
            ],
            [
                'national_id' => 'V-23456789',
                'first_name' => 'Carlos',
                'middle_name' => 'Eduardo',
                'last_name' => 'Pérez',
                'second_last_name' => 'Martínez',
                'birth_date' => '1975-10-22',
                'gender' => 'male',
                'civil_status' => 'divorced',
                'rif' => 'V-234567890',
                'email_1' => 'carlos.perez@ejemplo.com',
                'phone_number_1' => '0424-2345678',
                'address_line_1' => 'Urb. El Paraíso',
                'city' => 'Maracaibo',
                'state' => 'Zulia',
                'occupation' => 'Ingeniero',
            ],
            [
                'national_id' => 'V-34567890',
                'first_name' => 'Ana',
                'last_name' => 'González',
                'second_last_name' => 'Fernández',
                'birth_date' => '1990-03-08',
                'gender' => 'female',
                'civil_status' => 'single',
                'email_1' => 'ana.gonzalez@ejemplo.com',
                'phone_number_1' => '0412-3456789',
                'address_line_1' => 'Calle Bolívar',
                'city' => 'Valencia',
                'state' => 'Carabobo',
                'occupation' => 'Médico',
            ],
            [
                'national_id' => 'V-45678909',
                'first_name' => 'Luis',
                'middle_name' => 'Alberto',
                'last_name' => 'Ramírez',
                'birth_date' => '1985-07-30',
                'gender' => 'male',
                'civil_status' => 'married',
                'rif' => 'V-456789019',
                'email_1' => 'luis.ramirez@ejemplo.com',
                'phone_number_1' => '0416-4567890',
                'address_line_1' => 'Urb. Las Mercedes',
                'city' => 'Barquisimeto',
                'state' => 'Lara',
                'occupation' => 'Arquitecto',
            ],
            [
                'national_id' => 'V-56789012',
                'first_name' => 'Pedro',
                'last_name' => 'Mendoza',
                'second_last_name' => 'Rivera',
                'birth_date' => '1978-12-10',
                'gender' => 'male',
                'civil_status' => 'widowed',
                'email_1' => 'pedro.mendoza@ejemplo.com',
                'phone_number_1' => '0426-5678901',
                'address_line_1' => 'Av. Libertador',
                'city' => 'Mérida',
                'state' => 'Mérida',
                'occupation' => 'Profesor',
            ],
            [
                'national_id' => 'V-67890123',
                'first_name' => 'María',
                'middle_name' => 'Isabel',
                'last_name' => 'Torres',
                'second_last_name' => 'Gómez',
                'birth_date' => '1992-05-15',
                'gender' => 'female',
                'civil_status' => 'married',
                'email_1' => 'maria.torres@ejemplo.com',
                'phone_number_1' => '0414-6789012',
                'address_line_1' => 'Urb. El Trigal',
                'city' => 'Caracas',
                'state' => 'Distrito Capital',
                'occupation' => 'Abogada',
            ],
            [
                'national_id' => 'V-78901234',
                'first_name' => 'Carlos',
                'last_name' => 'Hernández',
                'birth_date' => '1988-09-22',
                'gender' => 'male',
                'civil_status' => 'single',
                'email_1' => 'carlos.hernandez@ejemplo.com',
                'phone_number_1' => '0424-7890123',
                'address_line_1' => 'Av. Bolívar Norte',
                'city' => 'Valencia',
                'state' => 'Carabobo',
                'occupation' => 'Contador',
            ],
            [
                'national_id' => 'V-89012345',
                'first_name' => 'Laura',
                'middle_name' => 'Patricia',
                'last_name' => 'Díaz',
                'second_last_name' => 'Martínez',
                'birth_date' => '1995-11-30',
                'gender' => 'female',
                'civil_status' => 'single',
                'email_1' => 'laura.diaz@ejemplo.com',
                'phone_number_1' => '0416-8901234',
                'address_line_1' => 'Urb. La Viña',
                'city' => 'Maracaibo',
                'state' => 'Zulia',
                'occupation' => 'Psicóloga',
            ],
            [
                'national_id' => 'V-90123456',
                'first_name' => 'José',
                'middle_name' => 'Antonio',
                'last_name' => 'Rojas',
                'birth_date' => '1982-04-18',
                'gender' => 'male',
                'civil_status' => 'divorced',
                'email_1' => 'jose.rojas@ejemplo.com',
                'phone_number_1' => '0426-9012345',
                'address_line_1' => 'Av. Universidad',
                'city' => 'Mérida',
                'state' => 'Mérida',
                'occupation' => 'Ingeniero Civil',
            ],
            [
                'national_id' => 'V-01234567',
                'first_name' => 'Carmen',
                'last_name' => 'Vargas',
                'second_last_name' => 'Pérez',
                'birth_date' => '1991-08-25',
                'gender' => 'female',
                'civil_status' => 'married',
                'email_1' => 'carmen.vargas@ejemplo.com',
                'phone_number_1' => '0412-0123456',
                'address_line_1' => 'Urb. El Bosque',
                'city' => 'Barquisimeto',
                'state' => 'Lara',
                'occupation' => 'Dentista',
            ],
            [
                'national_id' => 'V-98765432',
                'first_name' => 'Roberto',
                'middle_name' => 'Carlos',
                'last_name' => 'Morales',
                'birth_date' => '1987-12-05',
                'gender' => 'male',
                'civil_status' => 'single',
                'email_1' => 'roberto.morales@ejemplo.com',
                'phone_number_1' => '0414-1234567',
                'address_line_1' => 'Av. Bolívar Sur',
                'city' => 'Valencia',
                'state' => 'Carabobo',
                'occupation' => 'Arquitecto',
            ],
            [
                'national_id' => 'V-87654321',
                'first_name' => 'Isabel',
                'last_name' => 'Suárez',
                'second_last_name' => 'Rodríguez',
                'birth_date' => '1993-06-12',
                'gender' => 'female',
                'civil_status' => 'single',
                'email_1' => 'isabel.suarez@ejemplo.com',
                'phone_number_1' => '0424-2345678',
                'address_line_1' => 'Urb. La Florida',
                'city' => 'Caracas',
                'state' => 'Distrito Capital',
                'occupation' => 'Médico',
            ],
            [
                'national_id' => 'V-76543210',
                'first_name' => 'Miguel',
                'middle_name' => 'Ángel',
                'last_name' => 'Guzmán',
                'birth_date' => '1984-03-28',
                'gender' => 'male',
                'civil_status' => 'married',
                'email_1' => 'miguel.guzman@ejemplo.com',
                'phone_number_1' => '0416-3456789',
                'address_line_1' => 'Av. Bolívar',
                'city' => 'Maracaibo',
                'state' => 'Zulia',
                'occupation' => 'Abogado',
            ],
            [
                'national_id' => 'V-45678901',
                'first_name' => 'Patricia',
                'last_name' => 'López',
                'second_last_name' => 'García',
                'birth_date' => '1994-09-15',
                'gender' => 'female',
                'civil_status' => 'single',
                'email_1' => 'patricia.lopez@ejemplo.com',
                'phone_number_1' => '0426-4567890',
                'address_line_1' => 'Urb. El Trigal',
                'city' => 'Caracas',
                'state' => 'Distrito Capital',
                'occupation' => 'Psicóloga',
            ],
            [
                'national_id' => 'V-56789013',
                'first_name' => 'Fernando',
                'middle_name' => 'José',
                'last_name' => 'Silva',
                'birth_date' => '1989-07-20',
                'gender' => 'male',
                'civil_status' => 'divorced',
                'email_1' => 'fernando.silva@ejemplo.com',
                'phone_number_1' => '0412-5678903',
                'address_line_1' => 'Av. Universidad',
                'city' => 'Mérida',
                'state' => 'Mérida',
                'occupation' => 'Ingeniero',
            ],
        ];

        foreach ($individuals as $individual) {
            Individual::create($individual);
        }
    }
}
