<?php

namespace Database\Seeders;

use App\Models\LegalEntity;
use Illuminate\Database\Seeder;

class LegalEntitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $legalEntities = [
            [
                'rif' => 'J-29876543-2',
                'business_name' => 'Inversiones Caracas, C.A.',
                'trade_name' => 'InverCaracas',
                'legal_entity_type' => 'compania_anonima',
                'registration_number' => 'Tomo 45, Folio 78',
                'registration_date' => '2010-05-20',
                'fiscal_address_line_1' => 'Av. Libertador, Edificio Centro Empresarial, Piso 5',
                'fiscal_city' => 'Caracas',
                'fiscal_state' => 'Distrito Capital',
                'email_1' => 'info@invercaracas.com.ve',
                'phone_number_1' => '0212-9876543',
                'website' => 'www.invercaracas.com.ve',
            ],
            [
                'rif' => 'J-30987654-3',
                'business_name' => 'Constructora Andes, S.R.L.',
                'trade_name' => 'CONANDES',
                'legal_entity_type' => 'sociedad_de_responsabilidad_limitada',
                'registration_number' => 'Tomo 32, Folio 56',
                'registration_date' => '2008-11-15',
                'fiscal_address_line_1' => 'Calle Sucre, Edificio Torres, Piso 3, Oficina 3-B',
                'fiscal_city' => 'Mérida',
                'fiscal_state' => 'Mérida',
                'email_1' => 'contacto@conandes.com.ve',
                'phone_number_1' => '0274-8765432',
                'website' => 'www.conandes.com.ve',
            ],
            [
                'rif' => 'J-12098765-4',
                'business_name' => 'Distribuidora Zulia, C.A.',
                'trade_name' => 'DisZulia',
                'legal_entity_type' => 'compania_anonima',
                'registration_number' => 'Tomo 67, Folio 90',
                'registration_date' => '2015-03-10',
                'fiscal_address_line_1' => 'Av. 5 de Julio, Centro Comercial Las Mercedes, Local 12',
                'fiscal_city' => 'Maracaibo',
                'fiscal_state' => 'Zulia',
                'email_1' => 'ventas@diszulia.com.ve',
                'phone_number_1' => '0261-7654321',
                'website' => 'www.diszulia.com.ve',
            ],
            [
                'rif' => 'J-45678901-1',
                'business_name' => 'Fundación Ayuda Social',
                'legal_entity_type' => 'fundacion',
                'registration_number' => 'Tomo 12, Folio 35',
                'registration_date' => '2012-09-05',
                'fiscal_address_line_1' => 'Urb. El Trigal, Calle Los Robles, Casa 45',
                'fiscal_city' => 'Valencia',
                'fiscal_state' => 'Carabobo',
                'email_1' => 'contacto@ayudasocial.org.ve',
                'phone_number_1' => '0241-6543210',
                'website' => 'www.ayudasocial.org.ve',
            ],
            [
                'rif' => 'J-56789012-1',
                'business_name' => 'Cooperativa Agrícola El Sembrador',
                'trade_name' => 'CoopSembrador',
                'legal_entity_type' => 'cooperativa',
                'registration_number' => 'Tomo 23, Folio 46',
                'registration_date' => '2014-06-18',
                'fiscal_address_line_1' => 'Carretera Nacional, Sector La Morita, Km 5',
                'fiscal_city' => 'Barquisimeto',
                'fiscal_state' => 'Lara',
                'email_1' => 'info@coopsembrador.com.ve',
                'phone_number_1' => '0251-5432109',
                'website' => 'www.coopsembrador.com.ve',
            ],
            [
                'rif' => 'J-67890123-7',
                'business_name' => 'Constructora Edificios Modernos, C.A.',
                'trade_name' => 'EdiMod',
                'legal_entity_type' => 'compania_anonima',
                'registration_number' => 'Tomo 45, Folio 91',
                'registration_date' => '2016-08-22',
                'fiscal_address_line_1' => 'Av. Bolívar Norte, Torre Empresarial, Piso 15',
                'fiscal_city' => 'Caracas',
                'fiscal_state' => 'Distrito Capital',
                'email_1' => 'info@edimod.com.ve',
                'phone_number_1' => '0212-4321098',
                'website' => 'www.edimod.com.ve',
            ],
            [
                'rif' => 'J-78901234-8',
                'business_name' => 'Asociación Civil Deportiva Venezuela',
                'legal_entity_type' => 'asociacion_civil',
                'registration_number' => 'Tomo 78, Folio 90',
                'registration_date' => '2017-04-15',
                'fiscal_address_line_1' => 'Urb. La Viña, Av. Principal, Casa 23',
                'fiscal_city' => 'Valencia',
                'fiscal_state' => 'Carabobo',
                'email_1' => 'contacto@deportivavenezuela.org.ve',
                'phone_number_1' => '0241-3210987',
                'website' => 'www.deportivavenezuela.org.ve',
            ],
            [
                'rif' => 'J-89012345-9',
                'business_name' => 'Inversiones Tecnológicas, S.A.',
                'trade_name' => 'InverTech',
                'legal_entity_type' => 'sociedad_anonima',
                'registration_number' => 'Tomo 56, Folio 78',
                'registration_date' => '2018-11-30',
                'fiscal_address_line_1' => 'Centro Empresarial, Torre Este, Piso 8',
                'fiscal_city' => 'Maracaibo',
                'fiscal_state' => 'Zulia',
                'email_1' => 'ventas@invertech.com.ve',
                'phone_number_1' => '0261-2109876',
                'website' => 'www.invertech.com.ve',
            ],
            [
                'rif' => 'J-90123456-0',
                'business_name' => 'Fundación Cultural Caracas',
                'legal_entity_type' => 'fundacion',
                'registration_number' => 'Tomo 34, Folio 56',
                'registration_date' => '2019-07-12',
                'fiscal_address_line_1' => 'Av. Universidad, Edificio Cultural, Piso 4',
                'fiscal_city' => 'Caracas',
                'fiscal_state' => 'Distrito Capital',
                'email_1' => 'info@culturalcaracas.org.ve',
                'phone_number_1' => '0212-1098765',
                'website' => 'www.culturalcaracas.org.ve',
            ],
            [
                'rif' => 'J-01234567-1',
                'business_name' => 'Cooperativa de Transporte Unido',
                'trade_name' => 'CoopTrans',
                'legal_entity_type' => 'cooperativa',
                'registration_number' => 'Tomo 89, Folio 12',
                'registration_date' => '2020-03-25',
                'fiscal_address_line_1' => 'Av. Principal de La Urbina, Local 15',
                'fiscal_city' => 'Caracas',
                'fiscal_state' => 'Distrito Capital',
                'email_1' => 'contacto@cooptrans.com.ve',
                'phone_number_1' => '0212-0987654',
                'website' => 'www.cooptrans.com.ve',
            ],
            [
                'rif' => 'J-12345678-2',
                'business_name' => 'Consultores Asociados, C.A.',
                'trade_name' => 'ConAsoc',
                'legal_entity_type' => 'compania_anonima',
                'registration_number' => 'Tomo 67, Folio 94',
                'registration_date' => '2021-09-18',
                'fiscal_address_line_1' => 'Centro Comercial Las Mercedes, Torre Norte, Piso 12',
                'fiscal_city' => 'Caracas',
                'fiscal_state' => 'Distrito Capital',
                'email_1' => 'info@conasoc.com.ve',
                'phone_number_1' => '0212-9876543',
                'website' => 'www.conasoc.com.ve',
            ],
            [
                'rif' => 'J-23456789-3',
                'business_name' => 'Asociación de Productores Agrícolas',
                'legal_entity_type' => 'asociacion_civil',
                'registration_number' => 'Tomo 45, Folio 92',
                'registration_date' => '2022-01-30',
                'fiscal_address_line_1' => 'Av. Bolívar Sur, Edificio Agrícola, Piso 3',
                'fiscal_city' => 'Barquisimeto',
                'fiscal_state' => 'Lara',
                'email_1' => 'contacto@productoresagricolas.org.ve',
                'phone_number_1' => '0251-8765432',
                'website' => 'www.productoresagricolas.org.ve',
            ],
            [
                'rif' => 'J-34567890-4',
                'business_name' => 'Inversiones Inmobiliarias del Este, S.A.',
                'trade_name' => 'InverEste',
                'legal_entity_type' => 'sociedad_anonima',
                'registration_number' => 'Tomo 23, Folio 93',
                'registration_date' => '2022-06-15',
                'fiscal_address_line_1' => 'Av. Francisco de Miranda, Torre Este, Piso 20',
                'fiscal_city' => 'Caracas',
                'fiscal_state' => 'Distrito Capital',
                'email_1' => 'ventas@invereste.com.ve',
                'phone_number_1' => '0212-7654321',
                'website' => 'www.invereste.com.ve',
            ],
            [
                'rif' => 'J-45678901-2',
                'business_name' => 'Fundación Educativa Futuro',
                'legal_entity_type' => 'fundacion',
                'registration_number' => 'Tomo 12, Folio 36',
                'registration_date' => '2023-02-28',
                'fiscal_address_line_1' => 'Urb. El Trigal, Calle Principal, Casa 78',
                'fiscal_city' => 'Valencia',
                'fiscal_state' => 'Carabobo',
                'email_1' => 'info@futuroeducativo.org.ve',
                'phone_number_1' => '0241-6543210',
                'website' => 'www.futuroeducativo.org.ve',
            ],
            [
                'rif' => 'J-56789012-2',
                'business_name' => 'Cooperativa de Servicios Múltiples',
                'trade_name' => 'CoopServ',
                'legal_entity_type' => 'cooperativa',
                'registration_number' => 'Tomo 34, Folio 57',
                'registration_date' => '2023-08-10',
                'fiscal_address_line_1' => 'Av. Bolívar Norte, Local 45',
                'fiscal_city' => 'Maracaibo',
                'fiscal_state' => 'Zulia',
                'email_1' => 'contacto@coopserv.com.ve',
                'phone_number_1' => '0261-5432109',
                'website' => 'www.coopserv.com.ve',
            ],
        ];

        foreach ($legalEntities as $legalEntity) {
            LegalEntity::create($legalEntity);
        }
    }
}
